const CATALOG = [
		{
			id: 'C1T1',
			popular: 'img/catalog/popular.png',
			name: 'Рюкзак Louis Vuitton Discovery',
			img: 'img/catalog/louis-vuitton.png',
			price: 150000,
		},
		{
			id: 'C1T2',
			popular: 'img/catalog/popular.png',
			name: 'Рюкзак Louis Vuitton Discovery',
			img: 'img/catalog/louis-vuitton.png',
			price: 150000,
		},
		{
			id: 'C1T3',
			popular: 'img/catalog/popular.png',
			name: 'Рюкзак Louis Vuitton Discovery',
			img: 'img/catalog/louis-vuitton.png',
			price: 150000,
		},
		{
			id: 'C1T4',
			popular: 'img/catalog/popular.png',
			name: 'Рюкзак Louis Vuitton Discovery',
			img: 'img/catalog/louis-vuitton.png',
			price: 150000,
		},
		{
			id: 'C1T5',
			popular: 'img/catalog/popular.png',
			name: 'Рюкзак Louis Vuitton Discovery',
			img: 'img/catalog/louis-vuitton.png',
			price: 150000,
		},
		{
			id: 'C1T6',
			popular: 'img/catalog/popular.png',
			name: 'Рюкзак Louis Vuitton Discovery',
			img: 'img/catalog/louis-vuitton.png',
			price: 150000,
		},
		{
			id: 'C1T7',
			popular: 'img/catalog/popular.png',
			name: 'Рюкзак Louis Vuitton Discovery',
			img: 'img/catalog/louis-vuitton.png',
			price: 150000,
		},
		{
			id: 'C1T8',
			popular: 'img/catalog/popular.png',
			name: 'Рюкзак Louis Vuitton Discovery',
			img: 'img/catalog/louis-vuitton.png',
			price: 150000,
		},
		{
			id: 'C1T9',
			popular: 'img/catalog/popular.png',
			name: 'Рюкзак Louis Vuitton Discovery',
			img: 'img/catalog/louis-vuitton.png',
			price: 150000,
		},
		{
			id: 'C1T10',
			popular: 'img/catalog/popular.png',
			name: 'Рюкзак Louis Vuitton Discovery',
			img: 'img/catalog/louis-vuitton.png',
			price: 150000,
		},
		{
			id: 'C1T11',
			popular: 'img/catalog/popular.png',
			name: 'Рюкзак Louis Vuitton Discovery',
			img: 'img/catalog/louis-vuitton.png',
			price: 150000,
		},
		{
			id: 'C1T12',
			popular: 'img/catalog/popular.png',
			name: 'Рюкзак Louis Vuitton Discovery',
			img: 'img/catalog/louis-vuitton.png',
			price: 150000,
		},
]
const CATALOG2 = [
		{
			id: 'C2T1',
			popular: 'img/catalog/popular.png',
			name: 'Рюкзак Louis Vuitton Discovery',
			img: 'img/catalog/small.png',
			price: 150000,
		},
		{
			id: 'C2T2',
			popular: 'img/catalog/popular.png',
			name: 'Рюкзак Louis Vuitton Discovery',
			img: 'img/catalog/small.png',
			price: 150000,
		},
		{
			id: 'C2T3',
			popular: 'img/catalog/popular.png',
			name: 'Рюкзак Louis Vuitton Discovery',
			img: 'img/catalog/small.png',
			price: 150000,
		},
		{
			id: 'C2T4',
			popular: 'img/catalog/popular.png',
			name: 'Рюкзак Louis Vuitton Discovery',
			img: 'img/catalog/small.png',
			price: 150000,
		},
		{
			id: 'C2T5',
			popular: 'img/catalog/popular.png',
			name: 'Рюкзак Louis Vuitton Discovery',
			img: 'img/catalog/small.png',
			price: 150000,
		},
		{
			id: 'C2T6',
			popular: 'img/catalog/popular.png',
			name: 'Рюкзак Louis Vuitton Discovery',
			img: 'img/catalog/small.png',
			price: 150000,
		},
		{
			id: 'C2T7',
			popular: 'img/catalog/popular.png',
			name: 'Рюкзак Louis Vuitton Discovery',
			img: 'img/catalog/small.png',
			price: 150000,
		},
		{
			id: 'C2T8',
			popular: 'img/catalog/popular.png',
			name: 'Рюкзак Louis Vuitton Discovery',
			img: 'img/catalog/small.png',
			price: 150000,
		},
		{
			id: 'C2T9',
			popular: 'img/catalog/popular.png',
			name: 'Рюкзак Louis Vuitton Discovery',
			img: 'img/catalog/small.png',
			price: 150000,
		},
		{
			id: 'C2T10',
			popular: 'img/catalog/popular.png',
			name: 'Рюкзак Louis Vuitton Discovery',
			img: 'img/catalog/small.png',
			price: 150000,
		},
		{
			id: 'C2T11',
			popular: 'img/catalog/popular.png',
			name: 'Рюкзак Louis Vuitton Discovery',
			img: 'img/catalog/small.png',
			price: 150000,
		},
		{
			id: 'C2T12',
			popular: 'img/catalog/popular.png',
			name: 'Рюкзак Louis Vuitton Discovery',
			img: 'img/catalog/small.png',
			price: 150000,
		},
]
const CATALOG3 = [
		{
			id: 'C3T1',
			popular: 'img/catalog/popular.png',
			name: 'Рубашка Луи',
			img: 'img/catalog/sll.jpg',
			price: 15000,
		},
		{
			id: 'C3T2',
			popular: 'img/catalog/popular.png',
			name: 'Рубашка Луи',
			img: 'img/catalog/sll.jpg',
			price: 15000,
		},
		{
			id: 'C3T3',
			popular: 'img/catalog/popular.png',
			name: 'Рубашка Луи',
			img: 'img/catalog/sll.jpg',
			price: 15000,
		},
		{
			id: 'C3T4',
			popular: 'img/catalog/popular.png',
			name: 'Рубашка Луи',
			img: 'img/catalog/sll.jpg',
			price: 15000,
		},
		{
			id: 'C3T5',
			popular: 'img/catalog/popular.png',
			name: 'Рубашка Луи',
			img: 'img/catalog/sll.jpg',
			price: 15000,
		},
		{
			id: 'C3T6',
			popular: 'img/catalog/popular.png',
			name: 'Рубашка Луи',
			img: 'img/catalog/sll.jpg',
			price: 15000,
		},
		{
			id: 'C3T7',
			popular: 'img/catalog/popular.png',
			name: 'Рубашка Луи',
			img: 'img/catalog/sll.jpg',
			price: 15000,
		},
		{
			id: 'C3T8',
			popular: 'img/catalog/popular.png',
			name: 'Рубашка Луи',
			img: 'img/catalog/sll.jpg',
			price: 15000,
		},
		{
			id: 'C3T9',
			popular: 'img/catalog/popular.png',
			name: 'Рубашка Луи',
			img: 'img/catalog/sll.jpg',
			price: 15000,
		},
		{
			id: 'C3T10',
			popular: 'img/catalog/popular.png',
			name: 'Рубашка Луи',
			img: 'img/catalog/sll.jpg',
			price: 15000,
		},
		{
			id: 'C3T11',
			popular: 'img/catalog/popular.png',
			name: 'Рубашка Луи',
			img: 'img/catalog/sll.jpg',
			price: 15000,
		},
		{
			id: 'C3T12',
			popular: 'img/catalog/popular.png',
			name: 'Рубашка Луи',
			img: 'img/catalog/sll.jpg',
			price: 15000,
		},
]
